<?php
if ($this->name == 'index') {
	$this->title = $this->wiki['wiki_title'];
	$this->navigation = array($this->wiki['wiki_title']);
} else {
	$this->title = $this->page['page_title'];
	$this->navigation = array($this->wiki['wiki_title'], $this->page['page_title']);
}
?>

<div class="content">
	<?php flash(); ?>

	<form method="post" action="/<?php echo $this->wikiName; ?>/<?php echo wiki_filter($this->page['page_title']); ?>?action=save" class="stdForm">

		<div class="field">
			<label>Titel</label>
			<div class="textField">
				<input type="text" name="title" size="60" maxlength="100" value="<?php if ($this->page): ?><?php echo htmlspecialchars($this->page['page_title']); ?><?php endif; ?>" />
			</div>
		</div>

		<div class="field">
			<label>Inneh&aring;ll</label>
			<div class="textArea">
				<textarea name="text" rows="15" cols="60"><?php if ($this->page): ?><?php echo htmlspecialchars($this->page['page_text']); ?><?php endif; ?></textarea>
			</div>
		</div>

		<div class="button">
			<button type="submit">Spara</button>
		</div>
	</form>
</div>

<div style="clear: both;">&nbsp;</div>
