<?php
$this->title = 'Relationer';
$this->navigation = array('Community', $this->member['member_alias']);
?>

	<?php flash(); ?>

	<?php if ($_SESSION['id'] == $this->member['member_id'] && count($this->unapproved)): ?>
		<h3 class="bannerHeader">Ej godkända relationer</h3>
		<table class="default">
		<tr>
			<th class="left">Namn</th>
			<th style="width: 125px;">Text</th>
			<th style="width: 100px;">Har tr&auml;ffats?</th>
			<th style="width: 100px;">V&auml;nner sedan</th>
			<?php if ($this->member["member_id"] == $_SESSION["id"]): ?>
				<th style="width: 100px;">&nbsp;</th>
			<?php endif; ?>
		</tr>
		<?php foreach ($this->unapproved as $i => $relation): ?>
			<tr class="<?php echo ($i&1) == 0 ? 'even' : 'odd'; ?>">
				<td class="left"><a href="/profile/<?php echo $relation["member_flatalias"]; ?>"><?php echo $relation["member_alias"]; ?></a></td>
				<td><?php echo htmlspecialchars($relation["relation_action"]); ?></td>
				<td><?php echo $relation["relation_irl"] ? "Ja" : "Nej"; ?></td>
				<td><?php echo standardDate($relation["relation_timestamp"]); ?></td>
				<td>
					<?php if ($relation['relation_memberid2'] == $_SESSION['id']): ?>
						&raquo; <a href="/profile/<?php echo $relation['member_id']; ?>/relation/create">Acceptera</a><br />
					<?php endif; ?>
					<?php if ($this->member['member_id'] == $_SESSION['id']): ?>
						&raquo; <a href="#" onClick="confirmredir('Vill du verkligen bryta den här relationen?', '/profile/<?php echo $relation['member_id']; ?>/relation/deleteCommit?rid=<?php echo $relation['relation_id']; ?>');">Bryt relation</a>
					<?php endif; ?>
				</td>
			</tr>
		<?php endforeach; ?>
		</table>
			
	<?php endif; ?>
	
	<h3 class="bannerHeader">Godkända relationer</h3>
	<?php if (!count($this->approved)): ?>
		<div id="nofriends" class="bold text_large text_center">Inga vänner.</div>
	<?php else: ?>
		<table class="default">
		<tr>
			<th class="left">Namn</th>
			<th style="width: 125px;">Text</th>
			<th style="width: 100px;">Har tr&auml;ffats?</th>
			<th style="width: 100px;">V&auml;nner sedan</th>
			<?php if ($this->member["member_id"] == $_SESSION["id"]): ?>
				<th style="width: 100px;">&nbsp;</th>
			<?php endif; ?>
		</tr>
		<?php foreach ($this->approved as $i => $relation): ?>
			<tr class="<?php echo ($i&1) == 0 ? 'even' : 'odd'; ?>">
				<td class="left"><a href="/profile/<?php echo $relation["member_flatalias"]; ?>"><?php echo $relation["member_alias"]; ?></a></td>
				<td><?php echo htmlspecialchars($relation["relation_action"]); ?></td>
				<td><?php echo $relation["relation_irl"] ? "Ja" : "Nej"; ?></td>
				<td><?php echo standardDate($relation["relation_timestamp"]); ?></td>
				<?php if ($this->member["member_id"] == $_SESSION["id"]): ?>
					<td style="padding: 3px;">
						&raquo; <a href="#" onClick="confirmredir('Vill du verkligen bryta den här relationen?', '/profile/<?php echo $relation['member_id']; ?>/relation/deleteCommit?rid=<?php echo $relation['relation_id']; ?>');">Bryt relation</a>
					</td>
				<?php endif; ?>
			</tr>
		<?php endforeach; ?>
		</table>
	<?php endif; ?>

