<?php
function menuLink($page, $url, $text, $extraClass = "")
{
	list(,$current) = explode("/",$_SERVER["REQUEST_URI"]);

	if (!is_array($page)) {
		$page = array($page);
	}

	$class = "";
	if (in_array($current, $page)) {
		$class = "selected";
	} else {
		$class = "";
	}

	return sprintf('<li class="%s"><a href="%s">%s</a></li>', 
		implode(" ", array($extraClass, $class)), $url, $text);
}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Catahya<?php if ($_SESSION["online"] && $this->status['gbcount'] > 0) echo ' (' . $this->status['gbcount'] . ')'; ?></title>
	<style type="text/css">
		@import '/css/layout.css';
		<?php foreach ($this->css as $css): ?>
			@import '<?php echo $css; ?>';
		<?php endforeach; ?>
		
		<?php if (array_key_exists("style", $_SESSION)): ?>
		<?php if ($_SESSION["style"] == 2): ?>
		body {
			font-family: Verdana;
		}
		<?php elseif ($_SESSION["style"] == 3): ?>
		body {
			font-family: Arial;
		}
		<?php endif; ?>
		<?php endif; ?>
	</style>
	
	<script src="/js/jquery-1.3.1.min.js" type="text/javascript"></script>
	<script src="/js/ajax_functions.js" type="text/javascript"></script>
	<script src="/js/utilityscripts.js" type="text/javascript"></script>
	<script src="/js/update.js" type="text/javascript"></script>
	<?php foreach ($this->js as $js): ?>
		<script src="<?php echo $js; ?>" type="text/javascript"></script>
	<?php endforeach; ?>
	<script type="text/javascript">
	<?php if ($_SESSION["online"]): ?>
	$(document).ready(function() {
		setTimeout(updateFields, 300000);
	});
	<?php endif; ?>
	</script>
</head>

<body>
<div id="globalWrapper">
		<h1><div><span>Catahya</span></div></h1>
		
		<ul id="menu">
			<?php echo menuLink(array("", "start", "profile", "community", "message", "settings"), "/start", "Start"); ?>
			<?php echo menuLink("reviews", "/reviews", "Recensioner"); ?>
			<?php echo menuLink("chronicles", "/chronicles", "Krönikor"); ?>
			<?php echo menuLink("artwork", "/artwork", "Alster"); ?>
			<?php echo menuLink("forum", "/forum", "Forum"); ?>
			<?php echo menuLink("guilds", "/guilds", "Gillen"); ?>
			<?php echo menuLink("encyclopedia", "/encyclopedia", "Uppslagsverk"); ?>
			<?php //echo menuLink("store", "/store", "Butiken"); ?>
			<?php echo menuLink("irl", "/irl", "IRL"); ?>
			<?php echo menuLink("catahya", "/catahya", "Catahya"); ?>
			<?php echo menuLink("links", "/links", "Länkar"); ?>
			<?php if (Catahya_Access::hasAccess('admin')): ?>
				<?php echo menuLink("admin", "/admin", "Administration", "last"); ?>
			<?php else: ?>
			<?php endif; ?>
		</ul>
		
		<div id="contentWrapper">
			<div class="pageContent">
				
				<div class="menuColumn">
				
					<?php if (isset($this->pageMenu)): ?>
						<div class="box whiteBox">
							<div class="top">
								<div class="left">&nbsp;</div>
								<div class="right">&nbsp;</div>
							</div>
							<h2>Navigation</h2>
							<div class="content">
								<?php echo $this->pageMenu; ?>
							</div>
							<div class="bottom">
								<div class="left">&nbsp;</div>
								<div class="right">&nbsp;</div>
							</div>
						</div>	
					<?php endif; ?>
					
					<div class="box whiteBox">
						<div class="top">
							<div class="left">&nbsp;</div>
							<div class="right">&nbsp;</div>
						</div>
						<h2>Community</h2>
						<div class="content">
							<form method="get" action="/community/index/quicksearch">
								<div style="margin-top: 5px;">
									<label for="text" style="font-weight: normal;">Gå till medlem:</label>
									<div>
										<input type="q" name="q" id="q" style="width: 143px;" />
									</div>
								</div>
								
								<div style="text-align: right; margin-top: 5px;">
									<input type="submit" value="Sök" />
								</div>
							</form>
						</div>
						<div class="bottom">
							<div class="left">&nbsp;</div>
							<div class="right">&nbsp;</div>
						</div>
					</div>	
					
					<div class="box whiteBox">
						<div class="top">
							<div class="left">&nbsp;</div>
							<div class="right">&nbsp;</div>
						</div>
						<h2>Stil</h2>
						<div class="content">
						
							<a href="/index/style?style=1" style="display: block; background-color: #ccc; padding: 10px; margin-bottom: 10px;">
								Trebuchet MS
							</a>
							
							<a href="/index/style?style=2" style="display: block; background-color: #ccc; padding: 10px; margin-bottom: 10px;">
								Verdana
							</a>
							
							<a href="/index/style?style=3" style="display: block; background-color: #ccc; padding: 10px; margin-bottom: 10px;">
								Arial
							</a>
						</div>
						<div class="bottom">
							<div class="left">&nbsp;</div>
							<div class="right">&nbsp;</div>
						</div>
					</div>	
					
				</div>
				
				<div class="contentColumn">
				
					<div class="box whiteBox">
						<div class="top">
							<div class="left">&nbsp;</div>
							<div class="right">&nbsp;</div>
						</div>
						<h2>
							<div class="heading"><?php echo dotTruncate($this->title, 35); ?></div>
							<div class="navPath">
								Catahya
								<?php foreach ($this->navigation as $link => $page) echo ' &raquo; ' . (!is_numeric($link)?sprintf('<a href="%s">%s</a>',$link,$page):$page); ?>
							</div>
						</h2>
				
						<?php echo $this->content; ?>
					
						<div class="bottom">
							<div class="left">&nbsp;</div>
							<div class="right">&nbsp;</div>
						</div>
						
					</div>
				</div>
			
			</div>
			<div class="globalContent">
			
				<div class="box greenBox">
					<div class="top">
						<div class="left">&nbsp;</div>
						<div class="right">&nbsp;</div>
					</div>
					<?php if ($_SESSION['online']): ?>
						<h2><a href="javascript:updateFields()" id="friendsLink"><?php echo $_SESSION['alias']; ?></a></h2>
						<div id="user" class="content" style="padding: 10px 10px 10px 10px;">

							<ul class="subh menu" style="float: left; width: 90px; list-style-type: none; margin: 3px 0 0 0; padding: 0;">
								<li><a href="/profile/<?php echo $_SESSION['flatalias']; ?>">Profil</a></li>
								<li><a href="/settings/profile">Inställningar</a></li>
								<li><a href="/index/logoutCommit">Logga ut</a></li>
							</ul>
							<a class="avatar" href="/profile/<?php echo $_SESSION['flatalias']; ?>" style="display: block; float: right; width: 50px;">
								<img src="/userdata/avatars/50/<?php echo $_SESSION['photo']; ?>" alt="<?php echo $_SESSION['alias']; ?>" border="0" />
							</a>
							
							<div class="clear">&nbsp;</div>
						</div>
						
						<div class="content" style="border-top: 1px solid #ccc; margin-top: 0px;">
							<table style="width: 100%; font-size: 10pt; border-spacing: 0;">
								<tr>
									<td><a href="/message/index">Meddelanden</a></td>
									<td style="text-align: right; width: 50px;"><span id="messages_num"><?php echo $this->status['messcount']; ?></span> nya</td>
								</tr>
								<tr>
									<td><a href="/profile/<?php echo $_SESSION['flatalias']; ?>/guestbook">G&auml;stbok</a></td>
									<td style="text-align: right; width: 50px;"><span id="guestbook_num"><?php echo $this->status['gbcount']; ?></span> nya</td>
								</tr>
								<tr>
									<td><a href="/profile/<?php echo $_SESSION['flatalias']; ?>/relation">Relationer</a></td>
									<td style="text-align: right; width: 50px;"><span id="relations_num"><?php echo $this->status['relcount']; ?></span> nya</td>
								</tr>
							</table>
						</div>
						
						<!--<h2><a href="javascript:updateFields()" id="friendsLink">Vänner</a></h2>-->
						<div class="content" style="border-top: 1px solid #ccc; margin-top: 0px;">
							<table id="relations">
								<?php if (!count($this->relations)): ?>
									<tr><th class="norel">Inga relationer online.</th></tr>
								<?php else: ?>
										<?php foreach ($this->relations as $i => $relation): ?>
											<tr<?php if ($i == 0) echo ' class="first"'; ?>>
												<th><a href="/profile/<?php echo $relation['member_flatalias']; ?>"><?php echo $relation['member_alias']; ?></a></th>
												<td><a href="/profile/<?php echo $relation['member_flatalias']; ?>/guestbook">GB</a></td>
												<td><a href="/message/thread/write?to=<?php echo $relation['member_alias']; ?>">M</a></td>
											</tr>
										<?php endforeach; ?>
									<?php endif; ?>
								</table>
						</div>
						
						<div class="content" style="border-top: 1px solid #ccc; margin-top: 0px;">
							<?php if (!count($this->sidebarGuilds)): ?>
								Du är inte medlem i några <a href="/guilds">gillen</a>.
							<?php else: ?>
								<ul style="margin: 0; padding: 0; list-style-type: none;">
									<?php 
									$prevType = 0;
									foreach ($this->sidebarGuilds as $i => $guild):  ?>
										<li<?php if ($guild["guild_type"] != $prevType && $i > 0) echo ' style="margin-top: 10px;"'; ?>><a href="/guilds/<?php echo $guild["guild_id"]; ?>"><?php echo $guild["guild_name"]; ?></a></li>
									<?php 
									$prevType = $guild["guild_type"];
									endforeach; ?>
								</ul>
							<?php endif; ?>
						</div>
					<?php else: ?>
						<h2>Logga in</h2>
						<div id="user" class="content">
							<form method="post" action="/index/loginCommit">
								<input type="hidden" name="afterlogin" value="<?php echo $_SERVER["REQUEST_URI"]; ?>" />
								<div>
									<label for="username" style="font-weight: normal;">Användarnamn</label>
									<div>
										<input type="text" name="username" id="username" style="width: 143px;" />
									</div>
								</div>
								
								<div style="margin-top: 5px;">
									<label for="password" style="font-weight: normal;">Lösenord</label>
									<div>
										<input type="password" name="password" id="password" style="width: 143px;" />
									</div>
								</div>
								
								<div style="text-align: right; margin-top: 5px;">
									<input type="submit" value="Logga in" />
								</div>
							</form>
							<div style="margin-top: 10px;">
								<ul style="padding: 0; margin: 0; list-style-type: none;">
									<li><a href="/register/register">Registrera dig</a></li>
									<li>Glömt lösenord?</li>
									<li>Information om cookies</li>
								</ul>
							</div>
						</div>
					<?php endif; ?>
					<div class="bottom">
						<div class="left">&nbsp;</div>
						<div class="right">&nbsp;</div>
					</div>
				</div>
				
				<div class="box whiteBox">
					<div class="top">
						<div class="left">&nbsp;</div>
						<div class="right">&nbsp;</div>
					</div>
					<h2>Nya foruminlägg</h2>
					<div class="content">
						<?php foreach ($this->lastForumThreads as $news): ?>
							<p style="padding-bottom: 1px; padding-top: 1px; border-bottom: 1px dotted #ccc;"><a href="/forum/thread/<?php echo $news['thread_id']; ?>"><?php echo htmlspecialchars($news['thread_title']); ?></a></p>
						<?php endforeach; ?>
					</div>
					<div class="bottom">
						<div class="left">&nbsp;</div>
						<div class="right">&nbsp;</div>
					</div>
				</div>	
					
			</div>
		</div>
		
		<div id="footer" style="height: 35px; clear: both; background-image: url('/images/logo-bg.jpg'); background-position: bottom left; color: #fff; padding: 10px;">
			<div style="float: left; width: 45%;">
				Copyright &copy; Catahya 2007 - <?php echo date("Y"); ?>
			</div>
			<div style="float: right; width: 45%; text-align: right;">
				<?php if ($_SESSION["online"]): ?>
					Online sedan <span id="logintime"><?php echo date("H:i", $this->info["logintime"]); ?></span>
					(<span id="minonline"><?php echo $this->info["minonline"]; ?></span> minuter),
				<?php endif;  ?>
				<a href="/community/online/index" id="onlinecount"><?php echo $this->info["onlinecount"]; ?> <?php echo ($this->info["onlinecount"] == 1) ? "medlem" : "medlemmar"; ?></a> online<br />
				Senaste timmen:
				<span id="logincount"><?php echo $this->info["logincount"]; ?></span> inloggningar, 
				<span id="gbcount"><?php echo $this->info["gbcount"]; ?></span> gästboksinlägg,
				0 foruminlägg
			</div>

		</div>
</div>
</body>
</html>
