<?php
$this->title = 'Forum';
$this->navigation = array('Administration', 'Forum'); 
?>

<?php flash(); ?>

<div class="content">
	
	<p>
		Här kan du administrera Catahyas forum.
	</p>
	
</div>
	
<table class="default">
	<tr>
		<th class="left">Namn</th>
		<th>Kategori</th>
		<th>&nbsp;</th>
	</tr>
	<?php foreach ($this->forums as $i => $forum): ?>
		<tr class="<?php echo ($i&1) == 0 ? 'even' : 'odd'; ?>">
			<td class="left"><?php echo htmlspecialchars($forum['forum_name']); ?></td>
			<td><?php echo htmlspecialchars($forum['category_name']); ?></td>
			<td><a href="/admin/forum/edit?forumid=<?php echo $forum['forum_id']; ?>">Ändra</a></td>
		</tr>
	<?php endforeach; ?>
</table>

<div class="content">
	<p>
		<a href="/admin/forum/edit">Nytt forum</a>
	</p>
</div>

