<?php
$this->title = "Klar!";
$this->navigation = array('Community', 'Registrering');
?>

<div class="content">
	<p>
		Vi har skickat ut ett mail till adressen du angav. Detta mail
		innehåller en bekräftelselänk som du måste klicka på för
		att bekräfta ditt medlemskap.
	</p>

	<p style="padding-top: 10px;">
		<strong>OBS:</strong>
		Var uppmärksam på att ibland kan bekräftelsemail fastna i spamfilter. 
		Om du har sådant och inte har fått svar från oss är det kanske det 
		som har hänt.
	</p>
</div>
