<?php
$this->title = "Stadgar";
$this->navigation = array('Community', 'Registrering');
?>

<div class="content">
	<h3 class="subh">Kapitel I: Allmänna stadganden </h3>
	<div class="body">
		definition, syfte, bla bla
	</div>
	<h3 class="subh">Kapitel II: Medlemsskap</h3>
	<div class="body">
		Regler, medlemsskap ... bla ... <br /><br />
		<form method="post" action="/register/userinfo/">
			<input type="submit" name="submit_reg_page1" value="Godk&auml;nn Stadgarna">
		</form>
	</div>
</div>
